/**
 * KH AGRIFARM - PRELOADED LIVE DATASET FOR 4 PLOTS
 * Loaded directly from Google Sheets for instantaneous offline availability
 */

const SAMPLE_FARM_DATA = {
  "Season 6 PLOT 1": [
    { date: "24/06/2026", day: "Wed", stage: "HSS 1", month: 0, week: 1, task: "Semai bernih 35 tray dan simpan dalam stor kelap", spray: "", foliar: "", drip: "", ec: "" },
    { date: "25/06/2026", day: "Thu", stage: "HSS 2", month: 0, week: 1, task: "Buat Perangkap Lalat Buah 30 botols", spray: "", foliar: "", drip: "", ec: "" },
    { date: "26/06/2026", day: "Fri", stage: "HSS 3", month: 0, week: 1, task: "", spray: "", foliar: "", drip: "", ec: "" },
    { date: "27/06/2026", day: "Sat", stage: "HSS 4", month: 0, week: 1, task: "", spray: "", foliar: "", drip: "", ec: "" },
    { date: "28/06/2026", day: "Sun", stage: "HSS 5", month: 0, week: 1, task: "Cuci Paip & Repair Dripper", spray: "", foliar: "", drip: "", ec: "" },
    { date: "29/06/2026", day: "Mon", stage: "HSS 6", month: 0, week: 1, task: "Check benih kalau sudah campak akan pindah lawat petang", spray: "Cofenrin + Clean And Clear Sekeliling & Dalam Rumah Semai", foliar: "", drip: "", ec: "" },
    { date: "30/06/2026", day: "Tue", stage: "HSS 7", month: 0, week: 1, task: "Pindah ke rumah semai dan bagi air kosong\nSanitise sabut dengan 2 liter clorox dalam tangki", spray: "", foliar: "", drip: "", ec: "" },
    { date: "01/07/2026", day: "Wed", stage: "HSS 8", month: 0, week: 2, task: "bagi air kosong\n- Ikat Tali Hijau", spray: "", foliar: "", drip: "", ec: "" },
    { date: "02/07/2026", day: "Thu", stage: "HSS 9", month: 0, week: 2, task: "- Ikat Tali Hijau", spray: "", foliar: "", drip: "", ec: "" },
    { date: "03/07/2026", day: "Fri", stage: "HSS 10", month: 0, week: 2, task: "- Ikat Tali Hijau.\nFlushing Sabun polybag dengan Air Kosong.", spray: "", foliar: "", drip: "", ec: "" },
    { date: "04/07/2026", day: "Sat", stage: "HSS 11", month: 0, week: 2, task: "Bila daun baru dah nampak bagi start baja AB dengan rendaman. Flushing Sabun polybag dengan Air Kosong.", spray: "Solomon 3ml dalam Rumah Semai", foliar: "", drip: "", ec: "0.8" },
    { date: "05/07/2026", day: "Sun", stage: "HSS 12", month: 0, week: 2, task: "", spray: "", foliar: "", drip: "", ec: "0.8" },
    { date: "06/07/2026", day: "Mon", stage: "HSS 13", month: 0, week: 2, task: "Flushing Sabun polybag dengan Air Kosong.", spray: "", foliar: "", drip: "", ec: "0.8" },
    { date: "07/07/2026", day: "Tue", stage: "HSS 14", month: 0, week: 2, task: "Hari 1\nmasukkan treatment sukatan 120 ml ke dalam pam 20 liter. Sembur 5 saat ke dalam setiap poly bag.", spray: "Solomon 3ml dalam Rumah Semai", foliar: "", drip: "", ec: "0.9" },
    { date: "08/07/2026", day: "Wed", stage: "HSS 15", month: 0, week: 3, task: "Hari 2\npuasa (tidak bagi apa-apa)", spray: "Rendam Seranade SC (Bacillus) dalam Rumah Semai pada pagi dan puasa 1 hari. 25ml/L", foliar: "", drip: "", ec: "1.0" },
    { date: "09/07/2026", day: "Thu", stage: "HSS 16", month: 0, week: 3, task: "Hari 3\nhabiskan air kosong dalam satu tangki (600 gelen) sekali jalan.", spray: "Solomon 3ml dalam Rumah Semai", foliar: "", drip: "", ec: "1.1" },
    { date: "10/07/2026", day: "Fri", stage: "HSS 17", month: 0, week: 3, task: "Hari 4\nmasukkan 2 botol new super bacillus ke dalam tangki air kosong, habiskan satu tangki sekali jalan", spray: "", foliar: "", drip: "2 x New Bacillus", ec: "1.2" },
    { date: "11/07/2026", day: "Sat", stage: "HSS 18", month: 0, week: 3, task: "Hari 5\npuasa (tidak bagi apa-apa)", spray: "", foliar: "", drip: "", ec: "1.3" },
    { date: "12/07/2026", day: "Sun", stage: "HSS 19", month: 0, week: 3, task: "Hari 6\nmasukkan 2 botol super turbo nila ke dalam tangki air kosong, habiskan satu tangki sekali jalan", spray: "Solomon 3ml dalam Rumah Semai", foliar: "", drip: "2 x Superturbo Nila", ec: "1.4" },
    { date: "13/07/2026", day: "Mon", stage: "HSS 20", month: 0, week: 3, task: "Hari 7\npuasa (tidak bagi apa-apa)\n- Buat Lubang Tanam", spray: "Semai 45 Trays untuk Plot 2", foliar: "", drip: "", ec: "1.6" },
    { date: "14/07/2026", day: "Tue", stage: "HSS 21", month: 0, week: 3, task: "Hari 8\nmasukkan baja AB pada waktu petang dengan EC 2.8, habiskan satu tangki\n- Buat Lubang Tanam", spray: "Sivento P 30ml dalam Rumah Semai\nRacun Seluruh Kebun Conferin + Clean & Clear", foliar: "", drip: "", ec: "1.8" },
    { date: "15/07/2026", day: "Wed", stage: "HSS 22", month: 0, week: 3, task: "", spray: "", foliar: "", drip: "", ec: "1.8" },
    { date: "16/07/2026", day: "Thu", stage: "HST 0", month: 1, week: 1, task: "Hari 9\nmasukkan anak pokok ke dalam poly bag pada waktu petang, kemudian drip baja AB dengan EC 2.8. habiskan 1 tangki", spray: "Neem Oil dalam rumah semai sebelum tanam", foliar: "", drip: "", ec: "2.3" },
    { date: "17/07/2026", day: "Fri", stage: "HST 1", month: 1, week: 1, task: "Drip hanya bila perlu", spray: "Postponed sebab hujuan.", foliar: "", drip: "", ec: "2.3" },
    { date: "18/07/2026", day: "Sat", stage: "HST 2", month: 1, week: 1, task: "", spray: "Sivento P + Mancozeb", foliar: "Oliga Chitosan", drip: "", ec: "2.3" },
    { date: "19/07/2026", day: "Sun", stage: "HST 3", month: 1, week: 1, task: "", spray: "Neem Oil", foliar: "", drip: "Siram Baja AB", ec: "2.3" },
    { date: "20/07/2026", day: "Mon", stage: "HST 4", month: 1, week: 1, task: "", spray: "", foliar: "", drip: "", ec: "2.3" },
    { date: "21/07/2026", day: "Tue", stage: "HST 5", month: 1, week: 1, task: "", spray: "Endure + Mancozeb", foliar: "Superturbo F1", drip: "", ec: "2.3" },
    { date: "22/07/2026", day: "Wed", stage: "HST 6", month: 1, week: 1, task: "Mula drip pagi dan puasa petang (8min)", spray: "Movento E", foliar: "", drip: "", ec: "2.3" },
    { date: "23/07/2026", day: "Thu", stage: "HST 7", month: 1, week: 2, task: "", spray: "Dione 50SC", foliar: "", drip: "Siram Baja AB", ec: "2.4" },
    { date: "24/07/2026", day: "Fri", stage: "HST 8", month: 1, week: 2, task: "Sulam 400 Pokok bagi plot 1", spray: "Neem Oil", foliar: "Super Amino", drip: "", ec: "2.4" },
    { date: "25/07/2026", day: "Sat", stage: "HST 9", month: 1, week: 2, task: "", spray: "", foliar: "", drip: "", ec: "2.4" },
    { date: "26/07/2026", day: "Sun", stage: "HST 10", month: 1, week: 2, task: "", spray: "Plenum 50WG + Super Gummy", foliar: "", drip: "", ec: "2.4" },
    { date: "27/07/2026", day: "Mon", stage: "HST 11", month: 1, week: 2, task: "", spray: "Super Gummy", foliar: "", drip: "", ec: "2.4" },
    { date: "28/07/2026", day: "Tue", stage: "HST 12", month: 1, week: 2, task: "", spray: "", foliar: "", drip: "", ec: "2.4" },
    { date: "29/07/2026", day: "Wed", stage: "HST 13", month: 1, week: 2, task: "", spray: "Sanmite 20WP + Super Gummy", foliar: "", drip: "", ec: "2.4" },
    { date: "30/07/2026", day: "Thu", stage: "HST 14", month: 1, week: 3, task: "Sulam 1K Pokok bagi plot 1", spray: "Super Gummy", foliar: "", drip: "Siram Baja AB", ec: "2.5" },
    { date: "31/07/2026", day: "Fri", stage: "HST 15", month: 1, week: 3, task: "Cabang Y & Tunas Air mula terbentuk\n(Pembesaran pokok)", spray: "BASF Inveris + Super Gummy", foliar: "", drip: "", ec: "2.5" },
    { date: "01/08/2026", day: "Sat", stage: "HST 16", month: 1, week: 3, task: "", spray: "Super Gummy", foliar: "Oliga Chitosan", drip: "Drip Sea Weed", ec: "2.5" },
    { date: "02/08/2026", day: "Sun", stage: "HST 17", month: 1, week: 3, task: "", spray: "", foliar: "", drip: "", ec: "2.5" },
    { date: "03/08/2026", day: "Mon", stage: "HST 18", month: 1, week: 3, task: "", spray: "Khoros 300", foliar: "Super Amino", drip: "", ec: "2.5" },
    { date: "04/08/2026", day: "Tue", stage: "HST 19", month: 1, week: 3, task: "Siram Baja AB", spray: "Super Gummy", foliar: "Oliga Chitosan", drip: "AB", ec: "2.5" },
    { date: "05/08/2026", day: "Wed", stage: "HST 20", month: 1, week: 3, task: "", spray: "", foliar: "", drip: "", ec: "2.5" },
    { date: "06/08/2026", day: "Thu", stage: "HST 21", month: 1, week: 4, task: "Siram Baja AB", spray: "Plenum 50WG + Super Gummy", foliar: "", drip: "AB", ec: "2.6" },
    { date: "07/08/2026", day: "Fri", stage: "HST 22", month: 1, week: 4, task: "Buang Tunas Air", spray: "Bio-Botava", foliar: "Oliga Chitosan", drip: "AB", ec: "2.6" },
    { date: "08/08/2026", day: "Sat", stage: "HST 23", month: 1, week: 4, task: "Buang Tunas Air", spray: "", foliar: "", drip: "", ec: "2.6" },
    { date: "09/08/2026", day: "Sun", stage: "HST 24", month: 1, week: 4, task: "", spray: "Bayer Sivanto P + Super Gummy", foliar: "", drip: "AB", ec: "2.6" },
    { date: "10/08/2026", day: "Mon", stage: "HST 25", month: 1, week: 4, task: "", spray: "", foliar: "", drip: "", ec: "2.6" },
    { date: "11/08/2026", day: "Tue", stage: "HST 26", month: 1, week: 4, task: "", spray: "BASF Inveris + Super Gummy", foliar: "Oliga Chitosan", drip: "AB", ec: "2.6" },
    { date: "12/08/2026", day: "Wed", stage: "HST 27", month: 1, week: 4, task: "", spray: "Bio-Botava + Galic Oil", foliar: "", drip: "", ec: "2.6" },
    { date: "13/08/2026", day: "Thu", stage: "HST 28", month: 1, week: 5, task: "", spray: "", foliar: "", drip: "Drip Sea Weed", ec: "2.7" },
    { date: "14/08/2026", day: "Fri", stage: "HST 29", month: 1, week: 5, task: "", spray: "Khoros 300 + Super Gummy + Mancozeb", foliar: "Super Amino", drip: "", ec: "2.7" },
    { date: "15/08/2026", day: "Sat", stage: "HST 30", month: 1, week: 5, task: "", spray: "Bio-Botava + Galic Oil", foliar: "Oliga Chitosan", drip: "", ec: "2.7" },
    { date: "16/08/2026", day: "Sun", stage: "HST 31", month: 1, week: 5, task: "Buang Daun Bawah Cabang Y", spray: "", foliar: "", drip: "", ec: "2.7" },
    { date: "17/08/2026", day: "Mon", stage: "HST 32", month: 2, week: 5, task: "Buang Daun Bawah Cabang Y", spray: "Plenum 50WG + Super Gummy", foliar: "Oliga Chitosan", drip: "", ec: "2.7" },
    { date: "18/08/2026", day: "Tue", stage: "HST 33", month: 2, week: 5, task: "Buang Daun Bawah Cabang Y", spray: "Bio-Botava + Galic Oil", foliar: "", drip: "", ec: "2.7" },
    { date: "19/08/2026", day: "Wed", stage: "HST 34", month: 2, week: 5, task: "Buang Daun Bawah Cabang Y", spray: "", foliar: "", drip: "Superturbo Nila", ec: "2.7" },
    { date: "20/08/2026", day: "Thu", stage: "HST 35", month: 2, week: 6, task: "Buang Daun Bawah Cabang Y", spray: "Sanmite 20WP + Super Gummy", foliar: "Super Amino", drip: "", ec: "2.8" },
    { date: "21/08/2026", day: "Fri", stage: "HST 36", month: 2, week: 6, task: "", spray: "Bio-Botava + Neem Oil", foliar: "", drip: "", ec: "2.8" },
    { date: "22/08/2026", day: "Sat", stage: "HST 37", month: 2, week: 6, task: "", spray: "", foliar: "", drip: "", ec: "2.8" },
    { date: "23/08/2026", day: "Sun", stage: "HST 38", month: 2, week: 6, task: "", spray: "BASF Inveris + Super Gummy", foliar: "Oliga Chitosan", drip: "", ec: "2.8" },
    { date: "24/08/2026", day: "Mon", stage: "HST 39", month: 2, week: 6, task: "", spray: "Bio-Botava + Galic Oil", foliar: "", drip: "", ec: "2.8" },
    { date: "25/08/2026", day: "Tue", stage: "HST 40", month: 2, week: 6, task: "", spray: "", foliar: "", drip: "Super Orange", ec: "2.8" },
    { date: "26/08/2026", day: "Wed", stage: "HST 41", month: 2, week: 6, task: "Buang Daun Bawah Cabang Y", spray: "Bayer Sivanto P + Super Gummy", foliar: "", drip: "2 x New Bacillus + Rootboom", ec: "2.8" },
    { date: "27/08/2026", day: "Thu", stage: "HST 42", month: 2, week: 7, task: "Buang Daun Bawah Cabang Y\n(Pembesaran buah)", spray: "Bio-Botava + Galic Oil", foliar: "", drip: "", ec: "2.8" },
    { date: "28/08/2026", day: "Fri", stage: "HST 43", month: 2, week: 7, task: "Buang Daun Bawah Cabang Y", spray: "", foliar: "Super Amino", drip: "", ec: "2.8" },
    { date: "29/08/2026", day: "Sat", stage: "HST 44", month: 2, week: 7, task: "Buang Daun Bawah Cabang Y", spray: "Plenum 50WG + Super Gummy", foliar: "", drip: "", ec: "2.8" },
    { date: "30/08/2026", day: "Sun", stage: "HST 45", month: 2, week: 7, task: "Buang Daun Bawah Cabang Y", spray: "Bio-Botava + Neem Oil", foliar: "", drip: "2 x Food Master", ec: "2.8" },
    { date: "31/08/2026", day: "Mon", stage: "HST 46", month: 2, week: 7, task: "Buang Daun Bawah Cabang Y", spray: "", foliar: "", drip: "", ec: "2.8" },
    { date: "01/09/2026", day: "Tue", stage: "HST 47", month: 2, week: 7, task: "Cuci Sabut", spray: "Khoros 300 + Super Gummy", foliar: "", drip: "", ec: "2.8" },
    { date: "02/09/2026", day: "Wed", stage: "HST 48", month: 2, week: 7, task: "Buang Daun Bawah Cabang Y", spray: "Bio-Botava + Galic Oil", foliar: "", drip: "PN", ec: "2.8" },
    { date: "05/09/2026", day: "Sat", stage: "HST 51", month: 2, week: 8, task: "", spray: "", foliar: "", drip: "2 x Super Orange", ec: "2.8" },
    { date: "08/09/2026", day: "Tue", stage: "HST 54", month: 2, week: 8, task: "", spray: "", foliar: "", drip: "2 x Superturbo Nila", ec: "2.8" },
    { date: "10/09/2026", day: "Thu", stage: "HST 56", month: 2, week: 9, task: "", spray: "", foliar: "", drip: "", ec: "3.0" },
    { date: "13/09/2026", day: "Sun", stage: "HST 59", month: 3, week: 9, task: "", spray: "", foliar: "", drip: "2 x New Bacillus + Rootboom", ec: "3.0" },
    { date: "14/09/2026", day: "Mon", stage: "HST 60", month: 3, week: 9, task: "", spray: "", foliar: "", drip: "CN", ec: "3.0" },
    { date: "18/09/2026", day: "Fri", stage: "HST 64", month: 3, week: 10, task: "Cili mungkin mula merah", spray: "", foliar: "", drip: "2 x Food Master", ec: "3.0" },
    { date: "22/09/2026", day: "Tue", stage: "HST 68", month: 3, week: 10, task: "", spray: "", foliar: "", drip: "PN", ec: "3.0" },
    { date: "25/09/2026", day: "Fri", stage: "HST 71", month: 3, week: 11, task: "", spray: "", foliar: "", drip: "2 x New Bacillus + Rootboom", ec: "3.0" },
    { date: "26/09/2026", day: "Sat", stage: "HST 72", month: 3, week: 11, task: "", spray: "", foliar: "", drip: "2 x Superturbo Nila", ec: "3.0" },
    { date: "29/09/2026", day: "Tue", stage: "HST 75", month: 3, week: 11, task: "Mula Petik Cili & Cuci Sabut", spray: "", foliar: "", drip: "AB", ec: "3.0" },
    { date: "04/10/2026", day: "Sun", stage: "HST 80", month: 3, week: 12, task: "", spray: "", foliar: "", drip: "SOP", ec: "3.0" },
    { date: "05/10/2026", day: "Mon", stage: "HST 81", month: 3, week: 12, task: "", spray: "", foliar: "", drip: "2 x Food Master", ec: "3.0" },
    { date: "07/10/2026", day: "Wed", stage: "HST 83", month: 3, week: 12, task: "", spray: "", foliar: "", drip: "MKP", ec: "3.0" },
    { date: "08/10/2026", day: "Thu", stage: "HST 84", month: 3, week: 13, task: "", spray: "", foliar: "", drip: "AB", ec: "3.5" },
    { date: "09/10/2026", day: "Fri", stage: "HST 85", month: 3, week: 13, task: "", spray: "", foliar: "", drip: "2 x Super Orange", ec: "3.5" },
    { date: "14/10/2026", day: "Wed", stage: "HST 90", month: 4, week: 13, task: "Kemuncak Peringkat 1", spray: "", foliar: "", drip: "", ec: "3.5" },
    { date: "14/11/2026", day: "Sat", stage: "HST 121", month: 5, week: 18, task: "", spray: "", foliar: "", drip: "Blackboom", ec: "3.5" },
    { date: "27/11/2026", day: "Fri", stage: "HST 134", month: 5, week: 20, task: "", spray: "Chlorfenapyr", foliar: "", drip: "AB", ec: "3.5" },
    { date: "30/11/2026", day: "Mon", stage: "HST 137", month: 5, week: 20, task: "", spray: "Abamectin", foliar: "", drip: "MKP", ec: "3.5" },
    { date: "02/12/2026", day: "Wed", stage: "HST 139", month: 5, week: 20, task: "", spray: "Diafenthiuron", foliar: "", drip: "", ec: "3.5" },
    { date: "04/12/2026", day: "Fri", stage: "HST 141", month: 5, week: 21, task: "", spray: "Endure", foliar: "", drip: "SOP", ec: "3.5" },
    { date: "07/12/2026", day: "Mon", stage: "HST 144", month: 5, week: 21, task: "Kemuncak Peringkat 2", spray: "Chlorfenapyr + Copper", foliar: "", drip: "MKP", ec: "3.5" },
    { date: "09/12/2026", day: "Wed", stage: "HST 146", month: 5, week: 21, task: "", spray: "Skip because forecast rain", foliar: "", drip: "Black Boom + Root Boom", ec: "3.5" },
    { date: "11/12/2026", day: "Fri", stage: "HST 148", month: 5, week: 22, task: "", spray: "Abematin + Ferro", foliar: "", drip: "AB", ec: "3.5" },
    { date: "14/12/2026", day: "Mon", stage: "HST 151", month: 6, week: 22, task: "", spray: "Diafenthiuron + CB", foliar: "", drip: "PN", ec: "3.5" }
  ],

  "Season 6 PLOT 2": [
    { date: "13/07/2026", day: "Mon", stage: "HSS 1", month: 0, week: 1, task: "Semai bernih 45 tray dan simpan dalam stor kelap", spray: "", foliar: "", drip: "", ec: "" },
    { date: "17/07/2026", day: "Fri", stage: "HSS 5", month: 0, week: 1, task: "Cuci Paip & Repair Dripper", spray: "", foliar: "", drip: "", ec: "" },
    { date: "18/07/2026", day: "Sat", stage: "HSS 6", month: 0, week: 1, task: "Check benih kalau sudah campak akan pindah lawat petang", spray: "Solomon + Copper Hydroxide Sekeliling & Dalam Rumah Semai", foliar: "", drip: "", ec: "" },
    { date: "19/07/2026", day: "Sun", stage: "HSS 7", month: 0, week: 1, task: "Pindah ke rumah semai dan bagi air kosong\nSanitise sabut dengan 2 liter clorox dalam tangki", spray: "", foliar: "", drip: "", ec: "" },
    { date: "20/07/2026", day: "Mon", stage: "HSS 8", month: 0, week: 2, task: "bagi air kosong\n- Ikat Tali Hijau", spray: "", foliar: "", drip: "", ec: "" },
    { date: "21/07/2026", day: "Tue", stage: "HSS 9", month: 0, week: 2, task: "- Ikat Tali Hijau", spray: "", foliar: "", drip: "", ec: "" },
    { date: "22/07/2026", day: "Wed", stage: "HSS 10", month: 0, week: 2, task: "- Ikat Tali Hijau.", spray: "Super margosa dalam rumah semai", foliar: "", drip: "", ec: "" },
    { date: "23/07/2026", day: "Thu", stage: "HSS 11", month: 0, week: 2, task: "Bila daun baru dah nampak bagi start baja AB dengan rendaman. Flushing Sabun polybag dengan Air Kosong.", spray: "", foliar: "", drip: "", ec: "0.8" },
    { date: "30/07/2026", day: "Thu", stage: "HSS 18", month: 0, week: 3, task: "", spray: "Solomon 6ml dalam Rumah Semai", foliar: "", drip: "", ec: "1.5" },
    { date: "01/08/2026", day: "Sat", stage: "HSS 20", month: 0, week: 3, task: "Flushing Sabun polybag dengan Air Kosong.", spray: "", foliar: "", drip: "", ec: "1.7" },
    { date: "02/08/2026", day: "Sun", stage: "HSS 21", month: 0, week: 3, task: "Hari 1\nmasukkan treatment sukatan 120 ml ke dalam pam 20 liter. Sembur 5 saat ke dalam setiap poly bag.", spray: "Solomon 6ml dalam Rumah Semai", foliar: "", drip: "", ec: "1.8" },
    { date: "03/08/2026", day: "Mon", stage: "HSS 22", month: 0, week: 4, task: "Hari 2\npuasa (tidak bagi apa-apa)\n- Ikat Sticker Kuming", spray: "", foliar: "", drip: "", ec: "1.8" },
    { date: "04/08/2026", day: "Tue", stage: "HSS 23", month: 0, week: 4, task: "Hari 3\nhabiskan air kosong dalam satu tangki (600 gelen) sekali jalan.\n- Ikat Sticker Kuming", spray: "Solomon 6ml dalam Rumah Semai", foliar: "", drip: "", ec: "1.9" },
    { date: "05/08/2026", day: "Wed", stage: "HSS 24", month: 0, week: 4, task: "Hari 4\nmasukkan 2 botol new super bacillus ke dalam tangki air kosong, habiskan satu tangki sekali jalan", spray: "", foliar: "", drip: "2 x New Bacillus", ec: "1.9" },
    { date: "06/08/2026", day: "Thu", stage: "HSS 25", month: 0, week: 4, task: "Hari 5\npuasa (tidak bagi apa-apa)", spray: "Sivento P 30ml dalam Rumah Semai\nRacun Seluruh Kebun Conferin + Clean & Clear", foliar: "", drip: "", ec: "2.0" },
    { date: "07/08/2026", day: "Fri", stage: "HSS 26", month: 0, week: 4, task: "Hari 6\nmasukkan 2 botol super turbo nila ke dalam tangki air kosong, habiskan satu tangki sekali jalan\n- Buat Lubang Tanam", spray: "", foliar: "", drip: "2 x Superturbo Nila", ec: "2.0" },
    { date: "08/08/2026", day: "Sat", stage: "HSS 27", month: 0, week: 4, task: "Hari 7\npuasa (tidak bagi apa-apa)\n- Buat Lubang Tanam", spray: "", foliar: "", drip: "", ec: "2.1" },
    { date: "09/08/2026", day: "Sun", stage: "HSS 28", month: 0, week: 4, task: "Hari 8\nmasukkan baja AB pada waktu petang dengan EC 2.3, habiskan satu tangka\n- Buat Lubang Tanam", spray: "", foliar: "", drip: "", ec: "2.1" },
    { date: "10/08/2026", day: "Mon", stage: "HST 0", month: 1, week: 1, task: "Hari 9\nmasukkan anak pokok ke dalam poly bag pada waktu petang, kemudian drip baja AB dengan EC 2.8. habiskan 1 tangki", spray: "Impride SC + Abisec EC + Clean & Clear", foliar: "Superturbo F1", drip: "AB", ec: "2.3" },
    { date: "11/08/2026", day: "Tue", stage: "HST 1", month: 1, week: 1, task: "Semai 45 Trays untuk plot 2", spray: "Sanmite WP", foliar: "PowerK 50", drip: "AB", ec: "2.3" },
    { date: "12/08/2026", day: "Wed", stage: "HST 2", month: 1, week: 1, task: "", spray: "", foliar: "", drip: "AB", ec: "2.3" },
    { date: "13/08/2026", day: "Thu", stage: "HST 3", month: 1, week: 1, task: "", spray: "Cofenrin EC + Rainstato SC", foliar: "", drip: "", ec: "2.3" },
    { date: "14/08/2026", day: "Fri", stage: "HST 4", month: 1, week: 1, task: "", spray: "Khoros 300 + Super Gummy + Mancozeb", foliar: "Super Amino", drip: "AB", ec: "2.3" },
    { date: "15/08/2026", day: "Sat", stage: "HST 5", month: 1, week: 1, task: "", spray: "Bio-Botava + Galic Oil", foliar: "Oliga Chitosan", drip: "", ec: "2.3" },
    { date: "17/08/2026", day: "Mon", stage: "HST 7", month: 1, week: 2, task: "Siram Super Power", spray: "", foliar: "", drip: "Drip Sea Weed", ec: "2.4" },
    { date: "18/08/2026", day: "Tue", stage: "HST 8", month: 1, week: 2, task: "", spray: "Impride SC + Abisec EC + Clean & Clear", foliar: "Superturbo F1", drip: "", ec: "2.4" },
    { date: "19/08/2026", day: "Wed", stage: "HST 9", month: 1, week: 2, task: "", spray: "Neem Oil", foliar: "", drip: "AB", ec: "2.4" },
    { date: "22/08/2026", day: "Sat", stage: "HST 12", month: 1, week: 2, task: "", spray: "Sanmite WP + Rainstato SC", foliar: "Super Amino", drip: "", ec: "2.4" },
    { date: "23/08/2026", day: "Sun", stage: "HST 13", month: 1, week: 2, task: "", spray: "Neem Oil", foliar: "Superturbo F1", drip: "2 x Superturbo Nila", ec: "2.4" },
    { date: "24/08/2026", day: "Mon", stage: "HST 14", month: 1, week: 3, task: "Cabang Y & Tunas Air mula terbentuk\n(Pembesaran pokok)", spray: "", foliar: "", drip: "Siram Baja AB", ec: "2.5" },
    { date: "25/08/2026", day: "Tue", stage: "HST 15", month: 1, week: 3, task: "Buang Tunas Air", spray: "Sanmite WP + Clean & Clear", foliar: "PowerK 50", drip: "", ec: "2.5" },
    { date: "27/08/2026", day: "Thu", stage: "HST 17", month: 1, week: 3, task: "Buang Tunas Air", spray: "Cofenrin EC + Rainstato SC", foliar: "PowerK 50", drip: "", ec: "2.5" },
    { date: "29/08/2026", day: "Sat", stage: "HST 19", month: 1, week: 3, task: "Buang Tunas Air", spray: "", foliar: "", drip: "PN", ec: "2.5" },
    { date: "30/08/2026", day: "Sun", stage: "HST 20", month: 1, week: 3, task: "Buang Tunas Air", spray: "Impride SC + Abisec EC + Clean & Clear", foliar: "Calsium Boron", drip: "", ec: "2.5" },
    { date: "31/08/2026", day: "Mon", stage: "HST 21", month: 1, week: 4, task: "Pokok mula berbunga", spray: "Neem Oil", foliar: "PowerK 50", drip: "Siram Baja AB", ec: "2.6" },
    { date: "01/09/2026", day: "Tue", stage: "HST 22", month: 1, week: 4, task: "Pindah pokok plot 2", spray: "", foliar: "", drip: "", ec: "2.6" },
    { date: "02/09/2026", day: "Wed", stage: "HST 23", month: 1, week: 4, task: "", spray: "Impride SC + Abisec EC + Clean & Clear", foliar: "Superturbo F1", drip: "2 x Super Orange", ec: "2.6" },
    { date: "03/09/2026", day: "Thu", stage: "HST 24", month: 1, week: 4, task: "", spray: "Neem Oil", foliar: "Calsium Boron", drip: "", ec: "2.6" },
    { date: "06/09/2026", day: "Sun", stage: "HST 27", month: 1, week: 4, task: "", spray: "Cofenrin EC + Rainstato SC", foliar: "PowerK 50", drip: "", ec: "2.6" },
    { date: "08/09/2026", day: "Tue", stage: "HST 29", month: 1, week: 5, task: "", spray: "Impride SC + Abisec EC + Clean & Clear", foliar: "Calsium Boron", drip: "", ec: "2.7" },
    { date: "10/09/2026", day: "Thu", stage: "HST 31", month: 1, week: 5, task: "Pokok mula berbuah", spray: "Cofenrin EC + Rainstato SC", foliar: "Super Amino", drip: "", ec: "2.7" },
    { date: "11/09/2026", day: "Fri", stage: "HST 32", month: 2, week: 5, task: "", spray: "", foliar: "", drip: "2 x New Bacillus + Rootboom", ec: "2.7" },
    { date: "12/09/2026", day: "Sat", stage: "HST 33", month: 2, week: 5, task: "Buang Daun Bawah Cabang Y", spray: "Impride SC + Abisec EC + Clean & Clear", foliar: "", drip: "", ec: "2.7" },
    { date: "13/09/2026", day: "Sun", stage: "HST 34", month: 2, week: 5, task: "Buang Daun Bawah Cabang Y", spray: "Neem Oil", foliar: "", drip: "", ec: "2.7" },
    { date: "16/09/2026", day: "Wed", stage: "HST 37", month: 2, week: 6, task: "Buang Daun Bawah Cabang Y", spray: "Sanmite WP + Rainstato SC", foliar: "Super Amino", drip: "PN", ec: "2.8" },
    { date: "19/09/2026", day: "Sat", stage: "HST 40", month: 2, week: 6, task: "", spray: "Impride SC + Abisec EC + Clean & Clear", foliar: "PowerK 50", drip: "", ec: "2.8" },
    { date: "21/09/2026", day: "Mon", stage: "HST 42", month: 2, week: 7, task: "Buang Daun Bawah Cabang Y\n(Pembesaran buah)", spray: "", foliar: "", drip: "2 x Food Master", ec: "2.8" },
    { date: "22/09/2026", day: "Tue", stage: "HST 43", month: 2, week: 7, task: "Buang Daun Bawah Cabang Y", spray: "Cofenrin EC + Rainstato SC", foliar: "Calsium Boron", drip: "", ec: "2.8" },
    { date: "25/09/2026", day: "Fri", stage: "HST 46", month: 2, week: 7, task: "Buang Daun Bawah Cabang Y", spray: "Impride SC + Abisec EC + Clean & Clear", foliar: "PowerK 50", drip: "2 x Super Orange", ec: "2.8" },
    { date: "28/09/2026", day: "Mon", stage: "HST 49", month: 2, week: 8, task: "", spray: "Cofenrin EC + Rainstato SC", foliar: "Superturbo F1", drip: "", ec: "2.8" },
    { date: "01/10/2026", day: "Thu", stage: "HST 52", month: 2, week: 8, task: "", spray: "Solomon + Clean & Clear", foliar: "Foliar Biru", drip: "", ec: "2.8" },
    { date: "02/10/2026", day: "Fri", stage: "HST 53", month: 2, week: 8, task: "", spray: "", foliar: "", drip: "2 x New Bacillus + Rootboom", ec: "2.8" },
    { date: "03/10/2026", day: "Sat", stage: "HST 54", month: 2, week: 8, task: "", spray: "", foliar: "", drip: "2 x Superturbo Nila", ec: "2.8" },
    { date: "04/10/2026", day: "Sun", stage: "HST 55", month: 2, week: 8, task: "", spray: "Cofenrin EC + Rainstato SC", foliar: "Benegro EX", drip: "", ec: "2.8" },
    { date: "07/10/2026", day: "Wed", stage: "HST 58", month: 2, week: 9, task: "", spray: "Impride SC + Abisec EC + Clean & Clear", foliar: "Bio Amina", drip: "", ec: "3.0" },
    { date: "08/10/2026", day: "Thu", stage: "HST 59", month: 3, week: 9, task: "", spray: "", foliar: "", drip: "2 x Food Master", ec: "3.0" },
    { date: "13/10/2026", day: "Tue", stage: "HST 64", month: 3, week: 10, task: "Cili mungkin mula merah", spray: "Sanmite WP + Infinito", foliar: "Super Amino", drip: "", ec: "3.0" },
    { date: "14/10/2026", day: "Wed", stage: "HST 65", month: 3, week: 10, task: "", spray: "", foliar: "", drip: "2 x Super Orange", ec: "3.0" },
    { date: "16/10/2026", day: "Fri", stage: "HST 67", month: 3, week: 10, task: "", spray: "Cofenrin EC + Rainstato SC", foliar: "", drip: "", ec: "3.0" },
    { date: "20/10/2026", day: "Tue", stage: "HST 71", month: 3, week: 11, task: "", spray: "Luna Experience", foliar: "", drip: "", ec: "3.0" },
    { date: "22/10/2026", day: "Thu", stage: "HST 73", month: 3, week: 11, task: "", spray: "Funguran-Oh + Endure", foliar: "", drip: "", ec: "3.0" },
    { date: "23/10/2026", day: "Fri", stage: "HST 74", month: 3, week: 11, task: "", spray: "", foliar: "", drip: "2 x New Bacillus + Rootboom", ec: "3.0" },
    { date: "24/10/2026", day: "Sat", stage: "HST 75", month: 3, week: 11, task: "Mula Petik Cili & Cuci Sabut", spray: "Seranade + Calcium Boron", foliar: "", drip: "2 x Superturbo Nila", ec: "3.0" },
    { date: "27/10/2026", day: "Tue", stage: "HST 78", month: 3, week: 12, task: "", spray: "Luna Experience", foliar: "", drip: "", ec: "3.0" },
    { date: "28/10/2026", day: "Wed", stage: "HST 79", month: 3, week: 12, task: "", spray: "", foliar: "", drip: "2 x Food Master", ec: "3.0" },
    { date: "29/10/2026", day: "Thu", stage: "HST 80", month: 3, week: 12, task: "", spray: "Funguran-Oh + Endure", foliar: "", drip: "", ec: "3.0" },
    { date: "31/10/2026", day: "Sat", stage: "HST 82", month: 3, week: 12, task: "", spray: "Seranade + Calcium Boron", foliar: "", drip: "", ec: "3.0" },
    { date: "03/11/2026", day: "Tue", stage: "HST 85", month: 3, week: 13, task: "", spray: "Cofenrin EC + Rainstato SC", foliar: "", drip: "", ec: "3.5" },
    { date: "05/11/2026", day: "Thu", stage: "HST 87", month: 3, week: 13, task: "", spray: "Impride SC + Abisec EC + Mancozap", foliar: "", drip: "2 x Super Orange", ec: "3.5" },
    { date: "07/11/2026", day: "Sat", stage: "HST 89", month: 3, week: 13, task: "", spray: "Seranade + Calcium Boron", foliar: "", drip: "", ec: "3.5" },
    { date: "08/11/2026", day: "Sun", stage: "HST 90", month: 4, week: 13, task: "Kemuncak Peringkat 1", spray: "", foliar: "", drip: "", ec: "3.5" }
  ],

  "Backup Trees Batch 1": [
    { date: "28/07/2026", day: "Tue", stage: "HSS 1", month: 0, week: 1, task: "Semai bernih 16 tray dan simpan dalam stor kelap", spray: "", foliar: "", drip: "", ec: "" },
    { date: "01/08/2026", day: "Sat", stage: "HSS 5", month: 0, week: 1, task: "Cuci Paip & Repair Dripper", spray: "", foliar: "", drip: "", ec: "" },
    { date: "02/08/2026", day: "Sun", stage: "HSS 6", month: 0, week: 1, task: "Check benih kalau sudah campak akan pindah lewat petang", spray: "Solomon + Copper Hydroxide Sekeliling & Dalam Rumah Semai", foliar: "", drip: "", ec: "" },
    { date: "03/08/2026", day: "Mon", stage: "HSS 7", month: 0, week: 1, task: "Pindah ke rumah semai dan bagi air kosong\nSanitise sabut dengan 2 liter clorox dalam tangki", spray: "", foliar: "", drip: "", ec: "" },
    { date: "04/08/2026", day: "Tue", stage: "HSS 8", month: 0, week: 2, task: "bagi air kosong\n- Ikat Tali Hijau", spray: "", foliar: "", drip: "", ec: "" },
    { date: "05/08/2026", day: "Wed", stage: "HSS 9", month: 0, week: 2, task: "- Ikat Tali Hijau", spray: "", foliar: "", drip: "", ec: "" },
    { date: "06/08/2026", day: "Thu", stage: "HSS 10", month: 0, week: 2, task: "- Ikat Tali Hijau.", spray: "Super margosa dalam rumah semai", foliar: "", drip: "", ec: "" },
    { date: "07/08/2026", day: "Fri", stage: "HSS 11", month: 0, week: 2, task: "Bila daun baru dah nampak bagi start baja AB dengan rendaman. Flushing Sabun polybag dengan Air Kosong.", spray: "", foliar: "", drip: "", ec: "0.8" },
    { date: "08/08/2026", day: "Sat", stage: "HSS 12", month: 0, week: 2, task: "", spray: "", foliar: "", drip: "", ec: "0.9" },
    { date: "09/08/2026", day: "Sun", stage: "HSS 13", month: 0, week: 2, task: "", spray: "", foliar: "", drip: "", ec: "1.0" },
    { date: "10/08/2026", day: "Mon", stage: "HSS 14", month: 0, week: 2, task: "", spray: "", foliar: "", drip: "", ec: "1.1" },
    { date: "11/08/2026", day: "Tue", stage: "HSS 15", month: 0, week: 3, task: "", spray: "", foliar: "", drip: "", ec: "1.2" },
    { date: "12/08/2026", day: "Wed", stage: "HSS 16", month: 0, week: 3, task: "", spray: "", foliar: "", drip: "", ec: "1.3" },
    { date: "13/08/2026", day: "Thu", stage: "HSS 17", month: 0, week: 3, task: "", spray: "", foliar: "", drip: "", ec: "1.4" },
    { date: "14/08/2026", day: "Fri", stage: "HSS 18", month: 0, week: 3, task: "", spray: "", foliar: "", drip: "", ec: "1.5" },
    { date: "15/08/2026", day: "Sat", stage: "HSS 19", month: 0, week: 3, task: "", spray: "", foliar: "", drip: "", ec: "1.6" },
    { date: "16/08/2026", day: "Sun", stage: "HSS 20", month: 0, week: 3, task: "", spray: "", foliar: "", drip: "", ec: "1.7" },
    { date: "17/08/2026", day: "Mon", stage: "HSS 21", month: 0, week: 3, task: "", spray: "", foliar: "", drip: "2 x New Bacillus", ec: "1.8" },
    { date: "18/08/2026", day: "Tue", stage: "HSS 22", month: 0, week: 3, task: "", spray: "", foliar: "", drip: "", ec: "1.8" },
    { date: "19/08/2026", day: "Wed", stage: "HSS 23", month: 0, week: 3, task: "", spray: "", foliar: "", drip: "2 x Superturbo Nila", ec: "1.9" },
    { date: "20/08/2026", day: "Thu", stage: "HSS 24", month: 0, week: 3, task: "", spray: "", foliar: "", drip: "", ec: "1.9" },
    { date: "21/08/2026", day: "Fri", stage: "HSS 25", month: 0, week: 3, task: "", spray: "", foliar: "", drip: "", ec: "2.0" },
    { date: "22/08/2026", day: "Sat", stage: "HSS 26", month: 0, week: 3, task: "", spray: "", foliar: "", drip: "", ec: "2.0" },
    { date: "23/08/2026", day: "Sun", stage: "HSS 27", month: 0, week: 3, task: "", spray: "", foliar: "", drip: "", ec: "2.1" },
    { date: "24/08/2026", day: "Mon", stage: "HSS 28", month: 0, week: 3, task: "", spray: "", foliar: "", drip: "", ec: "2.1" }
  ],

  "Backup Trees Batch 2": [
    { date: "12/08/2026", day: "Wed", stage: "HSS 1", month: 0, week: 1, task: "Semai bernih 15 tray dan simpan dalam stor kelap", spray: "", foliar: "", drip: "", ec: "" },
    { date: "13/08/2026", day: "Thu", stage: "HSS 2", month: 0, week: 1, task: "", spray: "", foliar: "", drip: "", ec: "" },
    { date: "14/08/2026", day: "Fri", stage: "HSS 3", month: 0, week: 1, task: "", spray: "", foliar: "", drip: "", ec: "" },
    { date: "15/08/2026", day: "Sat", stage: "HSS 4", month: 0, week: 1, task: "", spray: "", foliar: "", drip: "", ec: "" },
    { date: "16/08/2026", day: "Sun", stage: "HSS 5", month: 0, week: 1, task: "Cuci Paip & Repair Dripper", spray: "", foliar: "", drip: "", ec: "" },
    { date: "17/08/2026", day: "Mon", stage: "HSS 6", month: 0, week: 1, task: "Check benih kalau sudah campak akan pindah lewat petang", spray: "Solomon + Copper Hydroxide Sekeliling & Dalam Rumah Semai", foliar: "", drip: "", ec: "" },
    { date: "18/08/2026", day: "Tue", stage: "HSS 7", month: 0, week: 1, task: "Pindah ke rumah semai dan bagi air kosong\nSanitise sabut dengan 2 liter clorox dalam tangki", spray: "", foliar: "", drip: "", ec: "" },
    { date: "19/08/2026", day: "Wed", stage: "HSS 8", month: 0, week: 2, task: "bagi air kosong\n- Ikat Tali Hijau", spray: "", foliar: "", drip: "", ec: "" },
    { date: "20/08/2026", day: "Thu", stage: "HSS 9", month: 0, week: 2, task: "- Ikat Tali Hijau", spray: "", foliar: "", drip: "", ec: "" },
    { date: "21/08/2026", day: "Fri", stage: "HSS 10", month: 0, week: 2, task: "- Ikat Tali Hijau.", spray: "Super margosa dalam rumah semai", foliar: "", drip: "", ec: "" },
    { date: "22/08/2026", day: "Sat", stage: "HSS 11", month: 0, week: 2, task: "Bila daun baru dah nampak bagi start baja AB dengan rendaman. Flushing Sabun polybag dengan Air Kosong.", spray: "", foliar: "", drip: "", ec: "0.8" },
    { date: "23/08/2026", day: "Sun", stage: "HSS 12", month: 0, week: 2, task: "", spray: "", foliar: "", drip: "", ec: "0.9" },
    { date: "24/08/2026", day: "Mon", stage: "HSS 13", month: 0, week: 2, task: "", spray: "", foliar: "", drip: "", ec: "1.0" },
    { date: "25/08/2026", day: "Tue", stage: "HSS 14", month: 0, week: 2, task: "", spray: "", foliar: "", drip: "", ec: "1.1" },
    { date: "26/08/2026", day: "Wed", stage: "HSS 15", month: 0, week: 3, task: "", spray: "", foliar: "", drip: "", ec: "1.2" },
    { date: "27/08/2026", day: "Thu", stage: "HSS 16", month: 0, week: 3, task: "", spray: "", foliar: "", drip: "", ec: "1.3" },
    { date: "28/08/2026", day: "Fri", stage: "HSS 17", month: 0, week: 3, task: "", spray: "", foliar: "", drip: "", ec: "1.4" },
    { date: "29/08/2026", day: "Sat", stage: "HSS 18", month: 0, week: 3, task: "", spray: "", foliar: "", drip: "", ec: "1.5" },
    { date: "30/08/2026", day: "Sun", stage: "HSS 19", month: 0, week: 3, task: "", spray: "", foliar: "", drip: "", ec: "1.6" },
    { date: "31/08/2026", day: "Mon", stage: "HSS 20", month: 0, week: 3, task: "", spray: "", foliar: "", drip: "", ec: "1.7" },
    { date: "01/09/2026", day: "Tue", stage: "HSS 21", month: 0, week: 3, task: "", spray: "", foliar: "", drip: "", ec: "1.8" },
    { date: "02/09/2026", day: "Wed", stage: "HSS 22", month: 0, week: 3, task: "", spray: "", foliar: "", drip: "", ec: "1.8" },
    { date: "03/09/2026", day: "Thu", stage: "HSS 23", month: 0, week: 3, task: "", spray: "", foliar: "", drip: "", ec: "1.9" },
    { date: "04/09/2026", day: "Fri", stage: "HSS 24", month: 0, week: 3, task: "", spray: "", foliar: "", drip: "", ec: "1.9" },
    { date: "05/09/2026", day: "Sat", stage: "HSS 25", month: 0, week: 3, task: "", spray: "", foliar: "", drip: "", ec: "2.0" },
    { date: "06/09/2026", day: "Sun", stage: "HSS 26", month: 0, week: 3, task: "", spray: "", foliar: "", drip: "", ec: "2.0" },
    { date: "07/09/2026", day: "Mon", stage: "HSS 27", month: 0, week: 3, task: "", spray: "", foliar: "", drip: "", ec: "2.1" },
    { date: "08/09/2026", day: "Tue", stage: "HSS 28", month: 0, week: 3, task: "", spray: "", foliar: "", drip: "", ec: "2.1" }
  ]
};

window.SAMPLE_FARM_DATA = SAMPLE_FARM_DATA;
